### MangoHud Configuration File

# display
position=top-left
font_size=22
background_alpha=0.4
alpha=1.0
round_corners=10
legacy_layout=false


# cpu
cpu_stats
cpu_temp
core_load
cpu_mhz

# gpu
gpu_stats
gpu_core_clock
gpu_mem_clock
gpu_power

# memory
ram
vram
swap

# performance
fps
frametime
# 1%, 5%, 10% low fps
fps_metrics=avg,0.01,0.05,0.10

# battery
battery
battery_watt
