keys:
    - &master_key age1jqqqf75ah2e7dgnfyeg8tjdssdelxgq38cepzvy7kwky7664lg5qtjfvyr

creation_rules:
    - path_regex: secrets/.*\.yaml$
      key_groups:
          - age:
                - *master_key
