# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "usbhid" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # disko manages these now.

  #fileSystems."/" =
  #  { device = "/dev/mapper/crypted";
  #    fsType = "btrfs";
  #    options = [ "subvol=root" ];
  #  };

  #boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/11810af3-d5d5-4aed-8948-bfd349628097";

  #fileSystems."/boot" =
  #  { device = "/dev/disk/by-uuid/3C96-0938";
  #    fsType = "vfat";
  #    options = [ "fmask=0077" "dmask=0077" ];
  #  };
  #
  #fileSystems."/home" =
  #  { device = "/dev/mapper/crypted";
  #    fsType = "btrfs";
  #    options = [ "subvol=home" ];
  #  };
  #
  #fileSystems."/nix" =
  #  { device = "/dev/mapper/crypted";
  #    fsType = "btrfs";
  #    options = [ "subvol=nix" ];
  #  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
